version: '3.10'

services:
  mysql_server:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: hsm1009_ind

  redis:
    image: redis

  gamesandplayers:
    image: gamesandplayers
    depends_on:
      - mysql_server
      - redis
    environment:
      - MYSQL_HOST=mysql_server
      - REDIS_HOST=redis
    ports:
      - "8080:8080"
